version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        VITE_API_ENDPOINT: 'https://demo-fs-app.azurewebsites.net:3001'
    image: demofsappregistry.azurecr.io/azure-docker-compose-ci-cd-demo_frontend:latest
    ports:
      - '80:80'
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: demofsappregistry.azurecr.io/azure-docker-compose-ci-cd-demo_backend:latest
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
