version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: demofsappregistry.azurecr.io/azure-docker-compose-ci-cd-demo_frontend:latest
    ports:
      - '80:80'
    restart: always
    environment:
      NODE_ENV: production
      